title:             Tina.R's Notebook
email:             tinaruan3@126.com
description:       A personal blog for recording code-learning process
author:            Tina Ruan
baseurl:           "/tinar3.github.io"
url:               "http://tinar3.github.io"

# Social Profiles
twitter_username:  
github_username:   tinar3
facebook_username: 
wechat_paccount_username:  product-diary

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
